version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/api
    environment:
      - WATCHPACK_POLLING=true
    command: sh -c "npm run start"
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:10.6.10
    container_name: conterise-teest-database
    restart: unless-stopped
    ports:
    -  "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: conterise-saas
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - mariadb-conterise:/var/lib/mysql
#Volumes
volumes:
  mariadb-conterise:
